name = "Distances"
uuid = "7223f906-ba81-40df-afcf-5b5d1b95bd28"
authors = ["Yan Figueiredo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
